### ISSUE TITLE
getAllDataFromVrmContinuously will probably blow the stack if the server runs for a long time

### ISSUE THREAD

**Issue by 3dGrabber** [3dGrabber/IeApi#3]
which it will.

`getAllDataFromVrmContinuously` calls itself, so it will add a stack frame on each iteration.
Since the program is intended to run essentially "forever", after a while stack space will be exhausted and a stackoverflow will occur.

replace with a loop.

(Node.js _might_ do tail call optimization, could not find any definitive answer if it does or not.
Anyways, I would not like to depend on it)

**Comment by simoor** [comment]
recursive function calls are garbage collected. 
see https://stackoverflow.com/questions/30263899/are-there-memory-leaks-with-javascript-call-a-function-in-a-callback-recursively#answer-30264130
